import { StrictMode} from 'react';
import { createRoot } from 'react-dom/client';
import { createBrowserRouter, RouterProvider } from "react-router-dom";
import { Amplify } from 'aws-amplify';
import outputs from '../amplify_outputs.json';

import type { ReactNode } from 'react';

import './index.css'
import App from './App.tsx'
import HomePage from "./pages/HomePage.tsx";
import ResumePage from "./pages/ResumePage.tsx";
import { initVisitorTracking } from './lib/visitorTracking.ts';

// Configure Amplify with outputs generated by Amplify Gen 2
Amplify.configure(outputs);

// Kick off visitor tracking (non-blocking)
void initVisitorTracking();

const router = createBrowserRouter([
    {
        path: '/',
        element: <App /> as ReactNode,
        children: [
            {
                index: true,
                element: <HomePage/> as ReactNode,
            },
            {
                path: 'resume',
                element: <ResumePage /> as ReactNode,
            },
        ],
    },
]);

createRoot(document.getElementById('root')!).render(
  (
    <StrictMode>
      <RouterProvider router={router} />
    </StrictMode>
  ) as ReactNode,
)
